Event default timestamp
jeffthibault/python-nostr pull request #24
Opened 2023-01-02 17:43 UTC by armstrys

Changed the `Event` default value for `created_at` to `None` and set time stamp within `__init__`. Also added a test file for events.

2023-01-16 13:36 UTC, callebtc commented on nostr/event.py
> +        self.created_at = created_at if created_at is not None else int(time.time())
```suggestion
        self.created_at = created_at or int(time.time())
```

;)

2023-01-16 13:37 UTC, callebtc requested changes
LGTM apart from the nit

2023-01-16 14:32 UTC, armstrys commented
Wow. I had never seen that solution. That’s going to save me a lot of text in my other work. Thanks :)

Also I wasn’t sure how to link it here, but this request will close [issue 23](https://github.com/jeffthibault/python-nostr/issues/23).

2023-01-16 15:05 UTC, jeffthibault commented
I'm not clear on why this change is needed. I think having the `created_at` time default to the current time is both logical and convenient.

If you want to use a custom time, you can do something similar to my suggestion in #23

2023-01-17 13:59 UTC, armstrys commented
I also left a comment on [#23](https://github.com/jeffthibault/python-nostr/issues/23), but wanted to leave one here to make sure it is clear. I agree that using the current time as a default is the most logical approach, but I don't think the current implementation behaves as expected - I see this PR as a bug fix as opposed to a new feature.

2023-01-19 19:28 UTC, jeffthibault commented
Thanks, I was able to reproduce the bug. LGTM

2023-01-19 19:29 UTC, merged

2023-01-20 14:44 UTC, kdmukai commented
@armstrys Can you add a follow-up update to document in the test what the test is addressing?

In general, each test should explain itself (`""" should use time of instantiation as..."""`) and in this case I'd also reference the Issue num/link as further explanation.

2023-01-21 14:30 UTC, kdmukai commented
Also I think a better test approach would be to create two `Event` instances w/a delay between them and verify that they have different `created_at` times.

2023-01-21 15:39 UTC, armstrys commented
Thanks for the feedback - That makes sense to me. Working on an update with both of those changes. Relatively new to contributions... can I push that update back up to this pull request or do I need to open a new one?

2023-01-21 15:42 UTC, kdmukai commented
New PR. But reference this one in the PR notes. If you write `#24` (just as normal text), github will autolink it: #24.

2023-01-21 16:20 UTC, armstrys commented
Okay, new PR is up and this all is making more sense. Thanks to both of you for your patience and help!